### ISSUE TITLE
Remove dotted line within Firefox

### ISSUE THREAD

**Issue by Olical** [alexwolfe/Buttons#3]
When clicking the buttons within Firefox it shows a dotted outline. This outline can be removed from anchor tags with this:

``` css
a:focus { 
    outline: none; 
}
```

If you are working with button tags, which I don't think you are, you can use this:

``` css
button::-moz-focus-inner {
    border: 0;
}
```

_[reference](http://stackoverflow.com/questions/71074/how-to-remove-firefoxs-dotted-outline-on-buttons-as-well-as-links)_
