### ISSUE TITLE
Shorten clearfix

### ISSUE THREAD

**Issue by KittyGiraudel** [alexwolfe/Buttons#47]
Any reason you still use an old version of the micro-clearfix: https://github.com/alexwolfe/Buttons/blob/master/scss/_mixins.scss#L39-L53?

You could switch to:

``` scss
.clearfix::after {
  content: '';
  display: table;
  clear: both;
}
```
